<?php
$title = 'Alocar recursos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<?php 
	$idMissao = $this->idMissao;
	$nomeAction = $this->serverUrl(true);
	$count = 0;
?>

<br />
<form action=<?php echo $nomeAction; ?> method="POST" name="alocarrecursos">

<input name="total" class="hidden" value=<?php echo $this->total; ?>>

<table class="table">
<tr>
	<th>Nome</th>
	<th>Quantidade</th>
	<th>&nbsp;</th>
</tr>
<tr>
	<?php foreach ($tiposRecurso as $tipoRecurso) : ?>
	<div class="form-group">
	<tr>
		<td><?php echo $this->escapeHtml($tipoRecurso->nome);?></td>
		<td><input class='form-control' name=<?php echo 'qtd'.$tipoRecurso->id ?> type="text" value="0"></td>
	</tr>
	<?php endforeach; ?>
	</div>
</tr>
</table>

<input type="submit" class="btn btn-primary" name="submit" value="Alocar recursos">
<a id="btn-voltar" class="btn btn-default" href="<?php echo $this->url('missao'); ?>">Voltar</a>

</form>

<script type="text/javascript">
	$(document).ready(function() {
		if (document.referrer.indexOf(window.location.hostname) != -1) {
			$('#btn-voltar').attr('href', document.referrer);
		}
	})
</script>
