



<?php
$title = 'Alocar recursos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<?php 
	$idMissao = $this->idMissao;
	$nomeAction = $this->serverUrl(true);
?>

<?php  
    $count = 0 ; ?>
<form action=<?php echo $nomeAction. $idMissao; ?> method="POST" name="alocarrecursos" onsubmit="validate()">
<input name="total" class="hidden" value=<?php echo $this->total; ?>>

<table class="table">
<tr>
	<th>Nome</th>
	<th>Quantidade</th>
	<th>&nbsp;</th>
</tr>

<tr>
<?php foreach ($tipoRecursos as $tipoRecurso) : ?>
<tr>
	<td>
		<?php echo $this->escapeHtml($tipoRecurso->nome);?>
	</td>
	<?php
		$idtipoRecurso = $tipoRecurso->id;
	?>
	<td>
		<?php $nome = "quantidade"; ?>
		<?php $idtipo = "id";
			$count = $count + 1; 
		?>
		<input name=<?php echo $idtipo. $count; ?> class="hidden" value=<?php echo $idtipoRecurso; ?>>
		<input name=<?php echo $nome. $count; ?> type="text" value="0">

	</td>
</tr>
<?php endforeach; ?>
</tr>

<tr>
	<td>
		<input type="submit" class="btn btn-default" name="submit" value="Alocar recursos">
	</td>
	<td>
		<input class='btn' name='submit' type='submit' value='Cancelar'>
	</td>
</tr>

</table>
</form>




<script type="text/javascript">
    alert( "ready!" );

$(document).ready(function() {
    alert( "ready!" );
});

function validate(){
    int total = document.getElementByName("total").val();
    alert(total);
    int i;
    String nameQ;

    for(i=1; i<=total;i++){
        nameQ = "quantidade" + i;

        if(!preg_match("/[^0-9\.\-\Ä\ä\Ö\ö\Ü\ü\ ]+$/s",document.getElementByName(nameQ).val())) {
            return TRUE; 
        }else{
            alert("Esta erradi!");
            return FALSE;
        } 
    }
}

</script>
