<?php
$title = 'Remover missão';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<br />
<p>Você tem certeza que deseja remover a missão abaixo?</p>
<br />

<table class="table">
<tr>
	<th>Data</th>
	<th>Nome</th>
	<th>Tipo de missão</th>
	<th>Protocolo</th>
	<th>Status</th>
</tr>
<tr>
	<td><?php echo $this->escapeHtml(date('d/m/Y', strtotime($missao->dataCriacao)));?></td>
	<td><?php echo $this->escapeHtml($missao->nome);?></td>
	<td><?php echo $this->escapeHtml($tipoMissao->nome);?></td>
	<td><?php echo $this->escapeHtml($missao->protocolo);?></td>
	<td><?php echo $this->escapeHtml($missao->statusNome);?></td>
</tr>
</table>

<?php $url = $this->url('missao', array('action' => 'delete', 'id' => $id,)); ?>

<form action="<?php echo $url; ?>" method="post">
<div>
	<input type="hidden" name="id" value="<?php echo (int) $missao->id; ?>" />
	<input type="hidden" name="redirect-url" value="<?php echo $redirectUrl; ?>" />
	<input type="submit" class="btn btn-danger" name="del" value="Sim" />
	<a id="btn-voltar" class="btn btn-default" href="<?php echo $this->url('missao'); ?>">Não</a>
</div>
</form>

<script type="text/javascript">
	$(document).ready(function() {
		if (document.referrer.indexOf(window.location.hostname) != -1) {
			$('#btn-voltar').attr('href', document.referrer);
		}
	})
</script>
