<?php
$title = 'Remover tipo de Missão';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Você tem certeza que deseja remover o tipo de missão 
<br>
'<?php echo $this->escapeHtml($tipoMissao->nome); ?>' ?
</p>

<?php
$url = $this->url('tipomissao', array(
	'action' => 'delete',
	'id'     => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $tipoMissao->id; ?>" />
    <input type="submit" class="btn btn-danger" name="del" value="Sim" />
    <input type="submit" class="btn" name="del" value="Não" />
</div>
</form>