<?php
$title = 'Detalhes da missão ';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<table class="table">
	<tr>
		<td>Data</td>
		<td><?php echo $this->escapeHtml(date('d/m/Y H:i:s', strtotime($Missao->dataCriacao))); ?></td>
	</tr>
	<tr>
		<td>Nome</td>
		<td><?php echo $this->escapeHtml($Missao->nome); ?></td>
	</tr>
	<tr>
		<td>Tipo de missao</td>
		<td><?php echo $this->escapeHtml($TipoMissao->nome); ?></td>
	</tr>
	<tr>
		<td>Protocolo</td>
		<td><?php echo $this->escapeHtml($Missao->protocolo); ?></td>
	</tr>
	<tr>
		<td>Status</td>
		<td><?php echo $this->escapeHtml($Missao->statusNome); ?></td>
	</tr>
</table>

<table class="table">
<tr>
    <th>Recurso</th>
    <th id="quantidade-th"></th>
</tr>
<?php if (count($recursosLista) == 0) { ?>
<tr>
	<td>Não existem recursos alocados para esta missão.</td>
	<td></td>
</tr>
<?php } else { ?>
<script type="text/javascript">
	$('#quantidade-th').html("Quantidade");
</script>
<?php foreach ($recursosLista as $recurso) : ?>
<tr>
	<td><?php echo $this->escapeHtml($recurso->nome); ?></td>
	<td><?php echo $this->escapeHtml($recurso->quantidade); ?></td>
</tr>
<?php endforeach; } ?>
</table>

<a id="btn-voltar" class="btn btn-default" href="<?php echo $this->url('missao'); ?>">Voltar</a>

<script type="text/javascript">
	$(document).ready(function() {
		if (document.referrer.indexOf(window.location.hostname) != -1) {
			$('#btn-voltar').attr('href', document.referrer);
		}
	})
</script>
