<?php
$title = 'Editar recursos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<?php 
	$nomeAction = $this->serverUrl(true);
	$count = 0;
?>

<br />

<table class="table">
<tr>
	<th>Nome</th>
	<th>Quantidade</th>
	<th>&nbsp;</th>
	<th>&nbsp;</th>
</tr>
<tr>
	<?php foreach ($editarRecursoLista as $recurso) : ?>
	<div class="form-group">
	<tr>
	<td>
		<?php echo $this->escapeHtml($recurso->nome);?></td>
	</td>
	<td>
		<?php echo $this->escapeHtml($recurso->quantidade);?></td>
	</td>
	<td>
		<a href="<?php echo $this->url('missao', array('action'=>'editarrecurso1', 'id' => $recurso->idRecurso));?>">Editar
	</td>
	<td>
		<a href="<?php echo $this->url('missao', array('action'=>'removerrecurso', 'id' => $recurso->idRecurso));?>">Remover
	</td>


	</tr>
	<?php endforeach; ?>
	</div>
</tr>
</table>

<a id="btn-novorecurso" class="btn btn-default" href="<?php echo $this->url('missao', array('action'=>'novorecurso', 'id' => $idMissao)); ?>">Alocar novo recurso</a>
<a id="btn-voltar" class="btn btn-default" href="<?php echo $this->url('missao', array('action'=>'editarrecursos', 'id' => $idMissao)); ?>">Voltar</a>

<script type="text/javascript">
	$(document).ready(function() {
		if (document.referrer.indexOf(window.location.hostname) != -1) {
			$('#btn-voltar').attr('href', document.referrer);
		}
	})
</script>
