<?php
$title = 'Alocar recursos';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>
<?php 
	$nomeAction = $this->serverUrl(true);
	$count = 0;
?>

<br />
<form action=<?php echo $nomeAction; ?> method="POST" name="editarrecurso1">

<table class="table">
<tr>
	<th>Nome</th>
	<th>Quantidade</th>

</tr>
<tr>
	<div class="form-group">
	<tr>
		<input class="hidden" name="idMissao" type="text" value="<?php echo $editarRecurso->idMissao ?>">
		<input class="hidden" name="idTipoRecurso" type="text" value="<?php echo $editarRecurso->idTipoRecurso ?>">
		<input class="hidden" name="idRecurso" type="text" value="<?php echo $editarRecurso->idRecurso ?>">

		<td><?php echo $this->escapeHtml($editarRecurso->nome);?></td>
		<td><input class='form-control' name="quantidade" style="width:100px" type="text" value="<?php echo $editarRecurso->quantidade ?>"></td>


	</tr>
	</div>
</tr>
</table>

<input type="submit" class="btn btn-primary" name="submit" value="Salvar">
<a id="btn-voltar" class="btn btn-default" href="<?php echo $this->url('missao'); ?>">Voltar</a>

</form>

<script type="text/javascript">
	$(document).ready(function() {
		if (document.referrer.indexOf(window.location.hostname) != -1) {
			$('#btn-voltar').attr('href', document.referrer);
		}
	})
</script>
