<?php
$title = 'Missões';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<?php
	$isAutenticado = isset($permissao) && $permissao;
	$isAdmin = $isAutenticado && $permissao == 'administrador';
	$isCoordenador = $isAutenticado && ($isAdmin || $permissao == 'coordenador');
?>

<hr class="divider">

<div class="span4 collapse-group">
	<h3><?php echo $this->escapeHtml('Filtros de busca');?></h3>
	<div class="collapse" id="viewdetails">
	TODO
	</div>
	<p><a class="btn" data-toggle="collapse" data-target="#viewdetails">Mostrar/Esconder &raquo;</a></p>
</div>

<hr class="divider">

<table class="table">
<tr>
	<th>Nome</th>
	<th>Status</th>
	<?php if ($isCoordenador) : ?><th>Recursos</th><?php endif; ?>
	<th>&nbsp;</th>
</tr>
<?php foreach ($Missoes as $Missao) : ?>
<tr>
	<td><?php echo $this->escapeHtml($Missao->nome);?></td>
	<td><?php echo $this->escapeHtml($Missao->statusNome);?></td>
	<?php
	if ($isCoordenador) {
		if ($Missao->recursosAlocados == "nao") {
	?>
	<td>
		<a href="<?php echo $this->url('missao', array('action'=>'alocarrecursos', 'id' => $Missao->id));?>">Alocar recursos</a> 
	</td>
	<?php } else { ?>
		<td></td>
	<?php
		} 
	}
	?>
	<td>
		<a href="<?php echo $this->url('missao', array('action'=>'detalhes', 'id' => $Missao->id));?>">Detalhes</a> 
	</td>
</tr>
<?php endforeach; ?>
</table>