<?php
$title = 'Remover usuário';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Você tem certeza que deseja remover o usuário de login
	'<?php echo $this->escapeHtml($usuario->login); ?>'?
</p>

<?php
$url = $this->url('usuario', array(
	'action' => 'delete',
	'id'     => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
<div>
	<input type="hidden" name="id" value="<?php echo (int) $usuario->id; ?>" />
	<input type="submit" name="del" value="Yes" />
	<input type="submit" name="del" value="No" />
</div>
</form>