<?php
$title = 'Editar senha';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
	'usuario',
	array(
		'action' => 'editpassword',
		'id'     => $this->id,
	)
));
$form->prepare();

echo $this->form()->openTag($form);
foreach ($form as $element) :?>
	<div class="form-group">
		<?php 
			if ($element->getOption('required')) { $req = 'required'; }
			$type = $element->getAttribute('type');
			$name = $element->getAttribute('name'); 
			$label = $element->getLabel();
			$value = $element->getValue();
		?>
		<?php if ($name == 'id') { ?>
			<div class="hidden"><?php echo $this->formElement($element); ?></div>
		<?php } else if ($name == 'submit') { ?>
			<input type='submit' class='btn btn-default' name='submit' value='<?php echo $value ?>'>
			<input class='btn' name='submit' type='submit' value='Cancelar'>
		<?php } else if ($type == 'select') {
			echo $this->formRow($form->get($name)); ?>
		<?php } else if ($label != '') { ?>
			<label class="control-label"><?php echo $label ?></label>
			<input class='form-control' name='<?php echo $name ?>' type='<?php echo $type ?>'
				value='<?php echo $value ?>'>
		<?php } ?> 
	</div>
<?php 
endforeach;
echo $this->form()->closeTag();

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}
?>