<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

		<?php echo $this->headMeta()
			->appendName('viewport', 'width=device-width, initial-scale=1.0')
			->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
		?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

		<!-- Scripts -->
		<?php echo $this->headScript()
			->prependFile($this->basePath() . '/js/bootstrap.min.js')
			->prependFile($this->basePath() . '/js/jquery.min.js')
			->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
			->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
		; ?>
		
		<!-- Cria algumas variáveis auxiliares para a criação do menu -->
		<?php
			$isAutenticado = isset($permissao) && $permissao;
			$isAdmin = $isAutenticado && $permissao == 'administrador';
			$isCoordenador = $isAdmin || $permissao == 'coordenador';
			$isEspecialista = $isAdmin || $permissao == 'especialista';
			$isLider = $isAdmin || $permissao == 'lider_missao';
			
			$uri = $this->serverUrl();
			$url = $this->serverUrl(true);
			$route = substr($url, strlen($uri) + 1);
		?>
		
	</head>
	<body>
		<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
				</div>
				<div class="collapse navbar-collapse">
					<ul class="nav navbar-nav">
						<li <?php if ($route == '' || strpos($route,'application') !== false || strpos($route,'index') !== false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->url('home'); ?>"><span class="glyphicon glyphicon-home"></span>&nbsp;&nbsp;<?php echo $this->translate('Home') ?></a>
						</li>
						
						<?php if ($isAutenticado): ?>
						<li <?php if (strpos($route,'success') !== false || strpos($route,'editpassword') !== false || strpos($route,'editdados') !== false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->url('login') ?>"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;<?php echo $this->translate('Perfil') ?></a>
						</li>
						<?php endif ?>
						
						<?php if ($isAdmin): ?>
						<li <?php if (strpos($route,'usuarios') !== false && strpos($route,'editpassword') === false && strpos($route,'editdados') === false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->basePath('usuarios') ?>"><?php echo $this->translate('Usuários') ?></a>
						</li>
						<?php endif ?>
						
						<?php if ($isAdmin): ?>
						<li <?php if (strpos($route,'tipomissao') !== false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->basePath('tipomissao') ?>"><?php echo $this->translate('Tipo de missão') ?></a>
						</li>
						<?php endif ?>
						
						<?php if ($isAdmin): ?>
						<li <?php if (strpos($route,'tiporecurso') !== false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->basePath('tiporecurso') ?>"><?php echo $this->translate('Tipo de recurso') ?></a>
						</li>
						<?php endif ?>

						<?php if ($isCoordenador): ?>
						<li <?php if (strpos($route,'acidente') !== false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->basePath('acidente') ?>"><?php echo $this->translate('Acidentes') ?></a>
						</li>
						<?php endif ?>
						
						<?php if ($isAdmin): ?>
						<li <?php if (strpos($route,'recurso') !== false && strpos($route,'tiporecurso') === false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->basePath('recurso') ?>"><?php echo $this->translate('Recursos') ?></a>
						</li>
						<?php endif ?>
						
						<?php if ($isAdmin): ?>
						<li <?php if (strpos($route,'missao') !== false && strpos($route,'tipomissao') === false && strpos($route,'missaoprotocolo') === false && strpos($route,'status') === false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->basePath('missao') ?>"><?php echo $this->translate('Missões');?></a>
						</li>						
						<?php endif ?>
						
						<?php if ($isLider): ?>
						<li <?php if (strpos($route,'missaoprotocolo') !== false || strpos($route,'status') !== false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->url('missao',array('action'=>'missaoprotocolo'));?>"><?php echo $this->translate('Atualizar status da missão') ?></a>
						</li>						
						<?php endif ?>
						
						<?php if ($isAutenticado): ?>
						<li <?php if (strpos($route,'logout') !== false): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>"><?php echo $this->translate('Logout') ?></a>
						</li>
						<?php else: ?>
						<li <?php if ((strpos($route,'login') !== false) || (strpos($route,'success') !== false)): ?>class="active"<?php endif ?>>
							<a href="<?php echo $this->basePath('login') ?>"><?php echo $this->translate('Login') ?></a>
						</li>
						<?php endif ?>
						
					</ul>
				</div><!--/.nav-collapse -->
			</div>
		</nav>
		<div class="container">
			<?php echo $this->content; ?>
			<hr>
			<footer>
				<p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
			</footer>
		</div> <!-- /container -->
		<?php echo $this->inlineScript() ?>
	</body>
</html>
