<?php
$title = 'Cadastrar acidente';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php 
$form->setAttribute('action', $this->url('acidente', array('action' => 'addAcidente')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('idAcidente')); 
?>

<ul>
	<li>
		<?php echo $this->formRow($form->get('localizacao')); ?>
	</li>
	<li>
		<?php echo $this->formRow($form->get('descricao')); ?>
	</li>
	<li>
		<?php echo $this->formRow($form->get('bombeiro')); ?>
	</li>
	<li>
		<?php echo $this->formRow($form->get('policia')); ?>
	</li>
	<li>
		<?php echo $this->formRow($form->get('obstrucao')); ?>
	</li>
</ul>

<?php 
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag(); 
?>