<?php
$title = 'Alocar missões';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<br />

<table class="table">
<tr>
    <th>Nome</th>
	<th>Tipo de missão</th>
</tr>
<?php if (count($missoes) == 0) { ?>
<tr>
	<td>Não existem missões alocadas para este acidente</td>
	<td></td>
</tr>
<?php } else { foreach ($missoes as $missao) : ?>
<tr>
    <td><?php echo $this->escapeHtml($missao->nome);?></td>
	<td><?php echo $this->escapeHtml($nomesTiposMissao[$missao->idTipoMissao]);?></td>
</tr>
<?php endforeach; } ?>
</table>

<a class="btn btn-primary" href="<?php echo $this->url('acidente', array('action'=>'salvarmissao', 'id'=>$idacidente)); ?>">Alocar nova missão</a>
<a class="btn btn-default" href="<?php echo $this->url('acidente', array('action'=>'info', 'id'=>$idacidente)); ?>">Finalizar alocação</a>
