<?php
$title = 'Remover acidente';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<br />
<p>Você tem certeza que deseja remover o acidente abaixo?</p>
<br />

<table class="table">
<tr>
	<th>Data</th>
	<th>Status</th>
	<th>Localização</th>
	<th>Descrição</th>
	<th>&nbsp;</th>
</tr>
<tr>
	<td><?php echo $this->escapeHtml(date('d/m/Y', strtotime($acidente->data)));?></td>
	<td><?php echo $this->escapeHtml($acidente->statusNome);?></td>
	<td><?php echo $this->escapeHtml($acidente->localizacao);?></td>
	<td><?php echo $this->escapeHtml($acidente->descricao);?></td>
</tr>
</table>

<?php $url = $this->url('acidente', array('action' => 'delete', 'id' => $id,)); ?>

<form action="<?php echo $url; ?>" method="post">
<div>
	<input type="hidden" name="id" value="<?php echo (int) $acidente->id; ?>" />
	<input type="submit" class="btn btn-danger" name="del" value="Sim" />
	<input type="submit" class="btn" name="del" value="Não" />
</div>
</form>