<?php
$title = 'Acidentes cadastrados';
$this->headTitle($title);
?>

<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a class='btn btn-default' href="<?php echo $this->url('acidente', array('action'=>'add'));?>">Adicionar Acidente</a>
</p>

<hr class="divider">

<div class="span4 collapse-group">
	<h3><?php echo $this->escapeHtml('Filtros de busca');?></h3>
	<div class="collapse" id="viewdetails">
	TODO
	</div>
	<p><a class="btn" data-toggle="collapse" data-target="#viewdetails">Mostrar/Esconder &raquo;</a></p>
</div>

<hr class="divider">


<?php
	$isAutenticado = isset($permissao) && $permissao;
	$isAdmin = $isAutenticado && $permissao == 'administrador';
	$isEspecialista = $isAutenticado && ($isAdmin || $permissao == 'especialista');
?>

<table class="table">
<tr>
    <th>Localização</th>
	<th>Descrição</th>
	<th>Data</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($acidentes as $acidente) : ?>
<tr>
    <td><?php echo $this->escapeHtml($acidente->localizacao);?></td>
	<td><?php echo $this->escapeHtml($acidente->descricao);?></td>
	<td><?php echo $this->escapeHtml(date('d/m/Y', strtotime($acidente->data)));?></td>
     <?php
	if ($isEspecialista) {
		if (!$missao->recursosAlocados) {
	?>
	<td>
		<a href="<?php echo $this->url('missao', array('action'=>'alocarrecursos', 'id' => $missao->id));?>">Alocar recursos</a> 
	</td>
	<?php } else { ?>
		<td></td>
	<?php
		} 
	}
	?>
    <td>
        <a href="<?php echo $this->url('acidente',
            array('action' => 'info', 'id' => $acidente->id));?>">Mais Informações</a>
    </td>
</tr>
<?php endforeach; ?>
</table>