<?php
$title = 'Informações do Acidente';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('acidente', array('action'=>'addMissao'));?>">Alocar Missão</a>
</p>

<table class="table">
<tr>
    <th>Localizacao</th>
	<th>Descricao</th>
	<th>Data</th>
    <th>Numero de Vitimas</th>
    <th>Bombeiro</th>
    <th>Policia</th>
    <th>Obstrucao</th>
    <th>&nbsp;</th>
</tr>
<tr>
    <td><?php echo $this->escapeHtml($acidente->localizacao);?></td>
	<td><?php echo $this->escapeHtml($acidente->descricao);?></td>
	<td><?php echo $this->escapeHtml($acidente->data);?></td>
	<td><?php echo $this->escapeHtml($acidente->numeroVitimas);?></td>
    <td><?php echo $this->escapeHtml($acidente->bombeiro);?></td>
    <td><?php echo $this->escapeHtml($acidente->policia);?></td>
    <td><?php echo $this->escapeHtml($acidente->obstrucao);?></td>
</tr>
</table>

<table class="table">
<tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th>Status</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($missoes as $missao) : ?>
<!-- implementar uma action que retorna o tipo de missao de cada missao -->
<tr>
    <td><?php echo $this->escapeHtml($tipoMissao->nome);?></td>
    <td><?php echo $this->escapeHtml($tipoMissao->descricao);?></td>
    <td><?php echo $this->escapeHtml($missao->status);?></td>
    <td>
        <a href="<?php echo $this->url('missao',
            array('action'=>'infoMissao', 'protocolo' => $missao->protocolo));?>">Mais Informações</a>
    </td>
<?php endforeach; ?>
</tr>