<?php
$title = 'Informações do acidente';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
	$isAutenticado = isset($permissao) && $permissao;
	$isAdmin = $isAutenticado && $permissao == 'administrador';
	$isCoordenador = $isAutenticado && ($isAdmin || $permissao == 'coordenador');
	$isEspecialista = $isAutenticado && ($isAdmin || $permissao == 'especialista');
?>

<br />

<table class="table" >
	<tr>
		<td>Data</td>
		<td><?php echo $this->escapeHtml(date('d/m/Y H:i:s', strtotime($acidente->data))); ?></td>
	</tr>
	<tr>
		<td>Status</td>
		<td><?php echo $this->escapeHtml($acidente->statusNome); ?></td>
	</tr>
	<tr>
		<td>Localização</td>
		<td><?php echo $this->escapeHtml($acidente->localizacao); ?></td>
	</tr>
	<tr>
		<td>Descrição</td>
		<td><?php echo $this->escapeHtml($acidente->descricao); ?></td>
	</tr>
	<tr>
		<td>Presença de bombeiros?</td>
		<td>
			<?php if ($acidente->bombeiro) : ?>
				<img src="<?php echo $this->basePath('img/ok.png') ?>" />
			<?php else : ?>
				<img src="<?php echo $this->basePath('img/nok.png') ?>" />
			<?php endif; ?>
		</td>
	</tr>
	<tr>
		<td>Presença de polícia?</td>
		<td>
			<?php if ($acidente->policia) : ?>
				<img src="<?php echo $this->basePath('img/ok.png') ?>" />
			<?php else : ?>
				<img src="<?php echo $this->basePath('img/nok.png') ?>" />
			<?php endif; ?>
		</td>
	</tr>
	<tr>
		<td>Número de vítimas</td>
		<td><?php echo $this->escapeHtml($acidente->numeroVitimas); ?></td>
	</tr>
	<tr>
		<td>Quantidade de obstruções na via</td>
		<td><?php echo $this->escapeHtml($acidente->obstrucao); ?></td>
	</tr>
</table>

<hr class="divider">
<div class="collapse" id="viewsvc" style="overflow: hidden;">
	<img style="display: inline; margin: 0 10px;" src="http://maps.googleapis.com/maps/api/staticmap?center=<?php echo $this->escapeHtml($lat); ?>,<?php echo $this->escapeHtml($lng); ?>&zoom=16&size=300x300&sensor=false">
	<img style="display: inline; margin: 0 10px;" src="http://maps.googleapis.com/maps/api/streetview?size=300x300&location=<?php echo $this->escapeHtml($lat); ?>,<?php echo $this->escapeHtml($lng); ?>&heading=235&fov=120&sensor=false">
</div>
<p><a class="btn" data-toggle="collapse" data-target="#viewsvc">Verificar SVC &raquo;</a></p>
<hr class="divider">
<br />

<table class="table">
<tr>
	<th>Missões alocadas</th>
	<th id="recursos-th"></th>
	<th>&nbsp;</th></tr>
<?php if (count($missoes) == 0) { ?>
<tr>
	<td>Não existem missões alocadas para este acidente</td>
	<td></td>
	<td></td>
</tr>
<?php } else { foreach ($missoes as $missao) : ?>
<tr>
	<td><?php echo $this->escapeHtml($missao->nome);?></td>
	<?php if ($isCoordenador && !$missao->recursosAlocados) { ?>
	<script type="text/javascript">
		$('#recursos-th').html("Recursos");
	</script>
	<td>
		<a href="<?php echo $this->url('missao', array('action'=>'alocarrecursos', 'id' => $missao->id));?>">Alocar recursos</a> 
	</td>
	<?php } else { ?>
		<td></td>
	<?php } ?>
	<td>
		<a href="<?php echo $this->url('missao', array('action'=>'detalhes', 'id' => $missao->id));?>">Detalhes</a> 
	</td>
</tr>
<?php endforeach; } ?>
</table>


<?php if ($isEspecialista && $acidente->status == 'cadastrado') { ?>
<a class='btn btn-primary' href="<?php echo $this->url('acidente', array('action'=>'alocarmissao', 
		'id'=>$acidente->id));?>">Alocar missões</a>
<?php } ?>

<a class="btn btn-default" href="<?php echo $this->url('acidente'); ?>">Voltar</a>
